In [3]:
#importing Libraries 
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

c:\Users\vshru\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
#loading data
dataset = load_dataset('lukebarousse/data_jobs')
df =dataset['train'].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
#Data Cleanup
df['job_posted_date']= pd.to_datetime(df['job_posted_date'])

In [ ]:
df

In [8]:
#apply() - Calculate projected salary for next year
#help(df.apply)

df_salary = df[pd.notna(df['salary_year_avg'])].copy()

In [ ]:
df_salary

In [11]:
df_salary['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [12]:
def projected_salary(salary):
    return salary*1.03    #3% inflation

In [9]:
df_salary['salary_year_inflated']=df_salary['salary_year_avg'].apply(projected_salary)

In [10]:
df_salary[['salary_year_avg','salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [11]:
df_salary['salary_year_inflated'] =df_salary['salary_year_avg'].apply(lambda salary:salary * 1.03)

In [12]:
df_salary[['salary_year_avg','salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [13]:
df_salary['salary_year_inflated'] =df_salary['salary_year_avg']*1.03

In [14]:
df_salary[['salary_year_avg','salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [15]:
df['job_skills']

0                                                       NaN
1         ['r', 'python', 'sql', 'nosql', 'power bi', 't...
2         ['python', 'sql', 'c#', 'azure', 'airflow', 'd...
3         ['python', 'c++', 'java', 'matlab', 'aws', 'te...
4         ['bash', 'python', 'oracle', 'aws', 'ansible',...
                                ...
785736    ['bash', 'python', 'perl', 'linux', 'unix', 'k...
785737                       ['sas', 'sas', 'sql', 'excel']
785738                              ['powerpoint', 'excel']
785739    ['python', 'go', 'nosql', 'sql', 'mongo', 'she...
785740                                      ['aws', 'flow']
Name: job_skills, Length: 785741, dtype: str

In [16]:
type(df['job_skills'][1])

str

In [17]:
#convert a string that looks like a list into an actual list is using abstract syntax trees.
import ast

# literal_eval. It "evaluates" the string and recognizes the Python data structure inside.
type(ast.literal_eval(df['job_skills'][1]))

list

In [18]:
#pd.notna -This line checks if the cell is "Not Available" (empty).
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)
    return skill_list #This ensures NaN stays NaN instead of becoming None

In [19]:
df['job_skills']=df['job_skills'].apply(clean_list)

In [21]:
type(df['job_skills'][6])

list

In [23]:
import ast
df['job_skills'] = df['job_skills'].apply(lambda skill_list:ast.literal_eval(skill_list) if pd.notna(skill_list)else skill_list)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [24]:
import ast 
df['job_skills'] = df['job_skills'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

In [25]:
df['job_skills'][1]

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [ ]:
df_salary

In [ ]:
#applying apply() to whole row 
def projected_salary(row):
    if "Senior" in row['job_title_short']:
        return 1.05 * row['salary_year_avg']
    else:
        return 1.03 * row['salary_year_avg']


df_salary['salary_year_inflated'] =df_salary.apply(projected_salary,axis =1)

In [15]:
df_salary[['job_title_short','salary_year_avg','salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]